const homescreenPaths = {
  bishopsList: require("../assets/json/bishopsList.json"),
  katamaros: require("../assets/json/menuJson/katamaros.json"),
  sundaysMonths: require("../assets/json/books/booksTable/Katamaros/months.json"),
  myHome: require("../assets/json/menuJson/mainMenu.json"),
  psalmody: require("../assets/json/menuJson/psalmody/psalmody.json"),
  liturgy: require("../assets/json/menuJson/liturgy/liturgy.json"),
  liturgyOfBelievers: require("../assets/json/menuJson/liturgy/liturgyBelievers.json"),
  liturgyOfBelieversCovenantThursday: require("../assets/json/menuJson/liturgy/liturgyBelieversCovenantThursday.json"),
  liturgyOfBelieversBrightSaturday: require("../assets/json/menuJson/liturgy/liturgyBelieversBrightSaturday.json"),
  liturgyofStBasil: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/liturgyofStBasil.json"),
  liturgyofStGregory: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/liturgyofStGregory.json"),
  liturgyOfWord: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/liturgyOfWord.json"),
  distribution: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/distribution.json"),
  LiturgyLiturgyOfTheWordPaplHymnsMenu: require("../assets/json/books/booksContent/Liturgy/LiturgyOfTheWord/papalHymns.json"),
  LiturgyLiturgyOfTheWordChantedLiturgyPsalm: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/chantedLiturgyPsalm.json"),
  LiturgyLiturgyOfTheWordChantedLiturgyPsalmPalmSunday1: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/chantedLiturgyPsalmPalmSunday1.json"),
  LiturgyLiturgyOfTheWordChantedLiturgyPsalmPalmSunday2: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/chantedLiturgyPsalmPalmSunday2.json"),
  LiturgyRaisingOfIncenseChantedVespersPsalm: require("../assets/json/books/booksTable/Liturgies/RaisingOfIncense/chantedVespersPsalm.json"),
  KatamarosTodaysReadings: require("../assets/json/books/booksTable/Katamaros/todaysReadings.json"),
  LiturgyRaisingOfIncenseChantedEveningPsalm: require("../assets/json/books/booksTable/Liturgies/RaisingOfIncense/chantedVespersPsalm.json"),
  LiturgyRaisingOfIncenseChantedMatinsPsalm: require("../assets/json/books/booksTable/Liturgies/RaisingOfIncense/chantedMatinsPsalm.json"),
  LiturgyRaisingOfIncenseProphecies: require("../assets/json/books/booksTable/Liturgies/RaisingOfIncense/prophecies.json"),
  LiturgyLiturgyOfTheWordCopticCatholic: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/copticCatholic.json"),
  LiturgyLiturgyOfTheWordCopticPauline: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/copticPaulineEpistle.json"),
  LiturgyLiturgyOfTheWordCopticActs: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/copticActs.json"),
  LiturgyLiturgyOfThBelieversAdamAspasmos: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/adamAspasmosMenu.json"),
  LiturgyLiturgyOfTheBelieversWatosAspasmos: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/watosAspasmosMenu.json"),
  LiturgyLiturgyOfTheBelieversFractions: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/fractions.json"),

  matrimony: require("../assets/json/books/booksTable/SpecialEvents/matrimony.json"),
  liturgyMenu: require("../assets/json/menuJson/liturgy/liturgyMenu.json"),
  pascha: require("../assets/json/menuJson/pascha/pascha.json"),
  saintsMelodies: require("../assets/json/books/booksTable/Venerations/saintsmelodies.json"),
  venerationsExposition: require("../assets/json/books/booksTable/Venerations/exposition.json"),
  bishopEntrance: require("../assets/json/books/booksTable/bishopEntrance.json"),
  index: require("../assets/json/menuJson//index.json"),
  vp: require("../assets/json/menuJson/psalmody/vesperspraises.json"),
  mp: require("../assets/json/menuJson/psalmody/midnightpraises.json"),
  eveningPrayers: require("../assets/json/books/booksTable/Liturgies/RaisingOfIncense/eveningPrayers.json"),
  paschaSunday: require("../assets/json/menuJson/pascha/sunday.json"),
  paschamondayeve: require("../assets/json/menuJson/pascha/mondayeve.json"),
  paschamonday: require("../assets/json/menuJson/pascha/monday.json"),
  paschatuesdayeve: require("../assets/json/menuJson/pascha/tuesdayeve.json"),
  paschatuesday: require("../assets/json/menuJson/pascha/tuesday.json"),
  paschawednesdayeve: require("../assets/json/menuJson/pascha/wednesdayeve.json"),
  paschawednesday: require("../assets/json/menuJson/pascha/wednesday.json"),
  paschathursdayeve: require("../assets/json/menuJson/pascha/thursdayeve.json"),
  paschathursday: require("../assets/json/menuJson/pascha/thursday.json"),
  paschafridayeve: require("../assets/json/menuJson/pascha/fridayeve.json"),
  paschafriday: require("../assets/json/menuJson/pascha/friday.json"),
  brightsaturday: require("../assets/json/menuJson/pascha/saturday.json"),
  //Table Of Contents
  morningDoxology: require("../assets/json/books/booksTable/Praises/MorningDoxology/morningDoxology"),
  standardPsalmody: require("../assets/json/books/booksTable/Praises/MidnightPraises/standardPsalmody.json"),
  kiahkPsalmody: require("../assets/json/books/booksTable/Praises/MidnightPraises/kiahkPsalmody.json"),
  lentenPsalmody: require("../assets/json/books/booksTable/Praises/MidnightPraises/lentenPsalmody.json"),
  standardVespersPraises: require("../assets/json/books/booksTable/Praises/VespersPraises//standardVespersPraises.json"),
  kiahkVespersPraises: require("../assets/json/books/booksTable/Praises/VespersPraises/kiahkVespersPraises.json"),
  lentenVespersPraises: require("../assets/json/books/booksTable/Praises/VespersPraises/lentenVespersPraises.json"),
  //Theotokias
  sundayTheotokiaMenu: require("../assets/json/books/booksTable/Praises/MidnightPraises/Theotokias/sundayTheotokiaMenu.json"),
  mondayTheotokiaMenu: require("../assets/json/books/booksTable/Praises/MidnightPraises/Theotokias/mondayTheotokiaMenu.json"),
  tuesdayTheotokiaMenu: require("../assets/json/books/booksTable/Praises/MidnightPraises/Theotokias/tuesdayTheotokiaMenu.json"),
  wednesdayTheotokiaMenu: require("../assets/json/books/booksTable/Praises/MidnightPraises/Theotokias/wednesdayTheotokiaMenu.json"),
  thursdayTheotokiaMenu: require("../assets/json/books/booksTable/Praises/MidnightPraises/Theotokias/thursdayTheotokiaMenu.json"),
  fridayTheotokiaMenu: require("../assets/json/books/booksTable/Praises/MidnightPraises/Theotokias/fridayTheotokiaMenu.json"),
  saturdayTheotokiaMenu: require("../assets/json/books/booksTable/Praises/MidnightPraises/Theotokias/saturdayTheotokiaMenu.json"),
  //veneration
  venerations: require("../assets/json/books/booksTable/Venerations/venerations.json"),
  //Doxologies
  doxologies: require("../assets/json/books/booksTable/Praises/MidnightPraises/doxologies.json"),
  //Liturgies
  offertory: require("../assets/json/books/booksTable/Liturgies/HolyLiturgy/offertory.json"),

  //RaisingOfIncense
  vespers: require("../assets/json/books/booksTable/Liturgies/RaisingOfIncense/vespers.json"),
  matins: require("../assets/json/books/booksTable/Liturgies/RaisingOfIncense/matins.json"),
  palmSundayProcession: require("../assets/json/books/booksContent/RaisingOfIncense/PalmSundayProcession.json"),
  //Pascha
  //Sunday
  //GeneralFuneral
  generalFuneral: require("../assets/json/books/booksTable/Pascha/Sunday/GeneralFuneral/generalFuneral.json"),
  generalFuneralcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Sunday/GeneralFuneral/copticPsalmAndGospel.json"),
  generalFuneralPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Sunday/GeneralFuneral/PsalmAndGospel.json"),
  generalFuneralcopticPaulineEpistle: require("../assets/json/books/booksTable/Pascha/Sunday/GeneralFuneral/copticPaulineEpistle.json"),
  generalFuneralPaulineEpistle: require("../assets/json/books/booksTable/Pascha/Sunday/GeneralFuneral/PaulineEpistle.json"),
  //SundayDay
  //NinthHour
  sundayDayNinthHourMain: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/NinthHour/mainPrayer.json"),
  sundayDayNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/NinthHour/copticPsalmAndGospel.json"),
  sundayDayNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/NinthHour/PsalmAndGospel.json"),
  sundayDayNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/NinthHour/copticProphecies.json"),
  sundayDayNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/NinthHour/Prophecies.json"),
  //Eleventh
  sundayDayEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/EleventhHour/mainPrayer.json"),
  sundayDayEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/EleventhHour/copticPsalmAndGospel.json"),
  sundayDayEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/EleventhHour/PsalmAndGospel.json"),
  sundayDayEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/EleventhHour/copticProphecies.json"),
  sundayDayEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Sunday/SundayDay/EleventhHour/Prophecies.json"),
  //MondayDay
  //FirstHour
  MondayDayFirstHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/FirstHour/mainPrayer.json"),
  MondayDayFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/FirstHour/copticPsalmAndGospel.json"),
  MondayDayFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/FirstHour/PsalmAndGospel.json"),
  MondayDayFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/FirstHour/copticProphecies.json"),
  MondayDayFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/FirstHour/Prophecies.json"),
  //ThirdHour
  MondayDayThirdHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/ThirdHour/mainPrayer.json"),
  MondayDayThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/ThirdHour/copticPsalmAndGospel.json"),
  MondayDayThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/ThirdHour/PsalmAndGospel.json"),
  MondayDayThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/ThirdHour/copticProphecies.json"),
  MondayDayThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/ThirdHour/Prophecies.json"),
  //Sixth
  MondayDaySixthHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/SixthHour/mainPrayer.json"),
  MondayDaySixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/SixthHour/copticPsalmAndGospel.json"),
  MondayDaySixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/SixthHour/PsalmAndGospel.json"),
  MondayDaySixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/SixthHour/copticProphecies.json"),
  MondayDaySixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/SixthHour/Prophecies.json"),
  //NinthHour
  MondayDayNinthHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/NinthHour/mainPrayer.json"),
  MondayDayNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/NinthHour/copticPsalmAndGospel.json"),
  MondayDayNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/NinthHour/PsalmAndGospel.json"),
  MondayDayNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/NinthHour/copticProphecies.json"),
  MondayDayNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/NinthHour/Prophecies.json"),
  //Eleventh
  MondayDayEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/EleventhHour/mainPrayer.json"),
  MondayDayEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/EleventhHour/copticPsalmAndGospel.json"),
  MondayDayEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/EleventhHour/PsalmAndGospel.json"),
  MondayDayEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/EleventhHour/copticProphecies.json"),
  MondayDayEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayDay/EleventhHour/Prophecies.json"),
  //MondayEve
  //FirstHour
  MondayEveFirstHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/FirstHour/mainPrayer.json"),
  MondayEveFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/FirstHour/copticPsalmAndGospel.json"),
  MondayEveFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/FirstHour/PsalmAndGospel.json"),
  MondayEveFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/FirstHour/copticProphecies.json"),
  MondayEveFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/FirstHour/Prophecies.json"),
  //ThirdHour
  MondayEveThirdHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/ThirdHour/mainPrayer.json"),
  MondayEveThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/ThirdHour/copticPsalmAndGospel.json"),
  MondayEveThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/ThirdHour/PsalmAndGospel.json"),
  MondayEveThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/ThirdHour/copticProphecies.json"),
  MondayEveThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/ThirdHour/Prophecies.json"),
  //Sixth
  MondayEveSixthHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/SixthHour/mainPrayer.json"),
  MondayEveSixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/SixthHour/copticPsalmAndGospel.json"),
  MondayEveSixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/SixthHour/PsalmAndGospel.json"),
  MondayEveSixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/SixthHour/copticProphecies.json"),
  MondayEveSixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/SixthHour/Prophecies.json"),
  //NinthHour
  MondayEveNinthHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/NinthHour/mainPrayer.json"),
  MondayEveNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/NinthHour/copticPsalmAndGospel.json"),
  MondayEveNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/NinthHour/PsalmAndGospel.json"),
  MondayEveNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/NinthHour/copticProphecies.json"),
  MondayEveNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/NinthHour/Prophecies.json"),
  //Eleventh
  MondayEveEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/EleventhHour/mainPrayer.json"),
  MondayEveEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/EleventhHour/copticPsalmAndGospel.json"),
  MondayEveEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/EleventhHour/PsalmAndGospel.json"),
  MondayEveEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/EleventhHour/copticProphecies.json"),
  MondayEveEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Monday/MondayEve/EleventhHour/Prophecies.json"),
  //TuesdayDay
  //FirstHour
  TuesdayDayFirstHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/FirstHour/mainPrayer.json"),
  TuesdayDayFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/FirstHour/copticPsalmAndGospel.json"),
  TuesdayDayFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/FirstHour/PsalmAndGospel.json"),
  TuesdayDayFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/FirstHour/copticProphecies.json"),
  TuesdayDayFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/FirstHour/Prophecies.json"),
  //ThirdHour
  TuesdayDayThirdHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/ThirdHour/mainPrayer.json"),
  TuesdayDayThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/ThirdHour/copticPsalmAndGospel.json"),
  TuesdayDayThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/ThirdHour/PsalmAndGospel.json"),
  TuesdayDayThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/ThirdHour/copticProphecies.json"),
  TuesdayDayThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/ThirdHour/Prophecies.json"),
  //Sixth
  TuesdayDaySixthHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/SixthHour/mainPrayer.json"),
  TuesdayDaySixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/SixthHour/copticPsalmAndGospel.json"),
  TuesdayDaySixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/SixthHour/PsalmAndGospel.json"),
  TuesdayDaySixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/SixthHour/copticProphecies.json"),
  TuesdayDaySixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/SixthHour/Prophecies.json"),
  //NinthHour
  TuesdayDayNinthHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/NinthHour/mainPrayer.json"),
  TuesdayDayNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/NinthHour/copticPsalmAndGospel.json"),
  TuesdayDayNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/NinthHour/PsalmAndGospel.json"),
  TuesdayDayNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/NinthHour/copticProphecies.json"),
  TuesdayDayNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/NinthHour/Prophecies.json"),
  //Eleventh
  TuesdayDayEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/EleventhHour/mainPrayer.json"),
  TuesdayDayEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/EleventhHour/copticPsalmAndGospel.json"),
  TuesdayDayEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/EleventhHour/PsalmAndGospel.json"),
  TuesdayDayEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/EleventhHour/copticProphecies.json"),
  TuesdayDayEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayDay/EleventhHour/Prophecies.json"),
  //TuesdayEve
  //FirstHour
  TuesdayEveFirstHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/FirstHour/mainPrayer.json"),
  TuesdayEveFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/FirstHour/copticPsalmAndGospel.json"),
  TuesdayEveFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/FirstHour/PsalmAndGospel.json"),
  TuesdayEveFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/FirstHour/copticProphecies.json"),
  TuesdayEveFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/FirstHour/Prophecies.json"),
  //ThirdHour
  TuesdayEveThirdHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/ThirdHour/mainPrayer.json"),
  TuesdayEveThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/ThirdHour/copticPsalmAndGospel.json"),
  TuesdayEveThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/ThirdHour/PsalmAndGospel.json"),
  TuesdayEveThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/ThirdHour/copticProphecies.json"),
  TuesdayEveThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/ThirdHour/Prophecies.json"),
  //Sixth
  TuesdayEveSixthHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/SixthHour/mainPrayer.json"),
  TuesdayEveSixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/SixthHour/copticPsalmAndGospel.json"),
  TuesdayEveSixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/SixthHour/PsalmAndGospel.json"),
  TuesdayEveSixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/SixthHour/copticProphecies.json"),
  TuesdayEveSixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/SixthHour/Prophecies.json"),
  //NinthHour
  TuesdayEveNinthHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/NinthHour/mainPrayer.json"),
  TuesdayEveNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/NinthHour/copticPsalmAndGospel.json"),
  TuesdayEveNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/NinthHour/PsalmAndGospel.json"),
  TuesdayEveNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/NinthHour/copticProphecies.json"),
  TuesdayEveNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/NinthHour/Prophecies.json"),
  //Eleventh
  TuesdayEveEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/EleventhHour/mainPrayer.json"),
  TuesdayEveEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/EleventhHour/copticPsalmAndGospel.json"),
  TuesdayEveEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/EleventhHour/PsalmAndGospel.json"),
  TuesdayEveEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/EleventhHour/copticProphecies.json"),
  TuesdayEveEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Tuesday/TuesdayEve/EleventhHour/Prophecies.json"),
  //WednesdayDay
  //FirstHour
  WednesdayDayFirstHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/FirstHour/mainPrayer.json"),
  WednesdayDayFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/FirstHour/copticPsalmAndGospel.json"),
  WednesdayDayFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/FirstHour/PsalmAndGospel.json"),
  WednesdayDayFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/FirstHour/copticProphecies.json"),
  WednesdayDayFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/FirstHour/Prophecies.json"),
  //ThirdHour
  WednesdayDayThirdHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/ThirdHour/mainPrayer.json"),
  WednesdayDayThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/ThirdHour/copticPsalmAndGospel.json"),
  WednesdayDayThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/ThirdHour/PsalmAndGospel.json"),
  WednesdayDayThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/ThirdHour/copticProphecies.json"),
  WednesdayDayThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/ThirdHour/Prophecies.json"),
  //Sixth
  WednesdayDaySixthHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/SixthHour/mainPrayer.json"),
  WednesdayDaySixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/SixthHour/copticPsalmAndGospel.json"),
  WednesdayDaySixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/SixthHour/PsalmAndGospel.json"),
  WednesdayDaySixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/SixthHour/copticProphecies.json"),
  WednesdayDaySixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/SixthHour/Prophecies.json"),
  //NinthHour
  WednesdayDayNinthHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/NinthHour/mainPrayer.json"),
  WednesdayDayNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/NinthHour/copticPsalmAndGospel.json"),
  WednesdayDayNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/NinthHour/PsalmAndGospel.json"),
  WednesdayDayNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/NinthHour/copticProphecies.json"),
  WednesdayDayNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/NinthHour/Prophecies.json"),
  //Eleventh
  WednesdayDayEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/EleventhHour/mainPrayer.json"),
  WednesdayDayEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/EleventhHour/copticPsalmAndGospel.json"),
  WednesdayDayEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/EleventhHour/PsalmAndGospel.json"),
  WednesdayDayEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/EleventhHour/copticProphecies.json"),
  WednesdayDayEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayDay/EleventhHour/Prophecies.json"),
  //WednesdayEve
  //FirstHour
  WednesdayEveFirstHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/FirstHour/mainPrayer.json"),
  WednesdayEveFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/FirstHour/copticPsalmAndGospel.json"),
  WednesdayEveFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/FirstHour/PsalmAndGospel.json"),
  WednesdayEveFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/FirstHour/copticProphecies.json"),
  WednesdayEveFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/FirstHour/Prophecies.json"),
  //ThirdHour
  WednesdayEveThirdHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/ThirdHour/mainPrayer.json"),
  WednesdayEveThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/ThirdHour/copticPsalmAndGospel.json"),
  WednesdayEveThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/ThirdHour/PsalmAndGospel.json"),
  WednesdayEveThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/ThirdHour/copticProphecies.json"),
  WednesdayEveThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/ThirdHour/Prophecies.json"),
  //Sixth
  WednesdayEveSixthHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/SixthHour/mainPrayer.json"),
  WednesdayEveSixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/SixthHour/copticPsalmAndGospel.json"),
  WednesdayEveSixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/SixthHour/PsalmAndGospel.json"),
  WednesdayEveSixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/SixthHour/copticProphecies.json"),
  WednesdayEveSixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/SixthHour/Prophecies.json"),
  //NinthHour
  WednesdayEveNinthHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/NinthHour/mainPrayer.json"),
  WednesdayEveNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/NinthHour/copticPsalmAndGospel.json"),
  WednesdayEveNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/NinthHour/PsalmAndGospel.json"),
  WednesdayEveNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/NinthHour/copticProphecies.json"),
  WednesdayEveNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/NinthHour/Prophecies.json"),
  //Eleventh
  WednesdayEveEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/EleventhHour/mainPrayer.json"),
  WednesdayEveEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/EleventhHour/copticPsalmAndGospel.json"),
  WednesdayEveEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/EleventhHour/PsalmAndGospel.json"),
  WednesdayEveEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/EleventhHour/copticProphecies.json"),
  WednesdayEveEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Wednesday/WednesdayEve/EleventhHour/Prophecies.json"),
  //ThursdayDay
  //FirstHour
  ThursdayDayFirstHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/FirstHour/mainPrayer.json"),
  ThursdayDayFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/FirstHour/copticPsalmAndGospel.json"),
  ThursdayDayFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/FirstHour/PsalmAndGospel.json"),
  ThursdayDayFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/FirstHour/copticProphecies.json"),
  ThursdayDayFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/FirstHour/Prophecies.json"),
  //ThirdHour
  ThursdayDayThirdHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/ThirdHour/mainPrayer.json"),
  ThursdayDayThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/ThirdHour/copticPsalmAndGospel.json"),
  ThursdayDayThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/ThirdHour/PsalmAndGospel.json"),
  ThursdayDayThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/ThirdHour/copticProphecies.json"),
  ThursdayDayThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/ThirdHour/Prophecies.json"),
  //Sixth
  ThursdayDaySixthHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/SixthHour/mainPrayer.json"),
  ThursdayDaySixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/SixthHour/copticPsalmAndGospel.json"),
  ThursdayDaySixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/SixthHour/PsalmAndGospel.json"),
  ThursdayDaySixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/SixthHour/copticProphecies.json"),
  ThursdayDaySixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/SixthHour/Prophecies.json"),
  //NinthHour
  ThursdayDayNinthHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/NinthHour/mainPrayer.json"),
  ThursdayDayNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/NinthHour/copticPsalmAndGospel.json"),
  ThursdayDayNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/NinthHour/PsalmAndGospel.json"),
  ThursdayDayNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/NinthHour/copticProphecies.json"),
  ThursdayDayNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/NinthHour/Prophecies.json"),
  //Laqan
  ThursdayDayLiturgyOfWaters: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/LiturgyOfWaters/mainprayer.json"),
  //Liturgy
  offertoryCovenantThursday: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/HolyLiturgy/offertory.json"),
  liturgyOfWordCovenantThursday: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/HolyLiturgy/liturgyOfWord.json"),
  copticPaulineEpistleCovenantThursday: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/HolyLiturgy/copticPaulineEpistle.json"),
  chantedLiturgyPsalmCovenantThursday: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/HolyLiturgy/chantedLiturgyPsalm.json"),
  liturgyofStBasilCovenantThursday: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/HolyLiturgy/liturgyofStBasil.json"),
  liturgyofStGregoryCovenantThursday: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/HolyLiturgy/liturgyofStGregory.json"),

  //Eleventh
  ThursdayDayEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/EleventhHour/mainPrayer.json"),
  ThursdayDayEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/EleventhHour/copticPsalmAndGospel.json"),
  ThursdayDayEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/EleventhHour/PsalmAndGospel.json"),
  ThursdayDayEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/EleventhHour/copticProphecies.json"),
  ThursdayDayEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayDay/EleventhHour/Prophecies.json"),
  //ThursdayEve
  //FirstHour
  ThursdayEveFirstHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/FirstHour/mainPrayer.json"),
  ThursdayEveFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/FirstHour/copticPsalmAndGospel.json"),
  ThursdayEveFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/FirstHour/PsalmAndGospel.json"),
  ThursdayEveFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/FirstHour/copticProphecies.json"),
  ThursdayEveFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/FirstHour/Prophecies.json"),
  //ThirdHour
  ThursdayEveThirdHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/ThirdHour/mainPrayer.json"),
  ThursdayEveThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/ThirdHour/copticPsalmAndGospel.json"),
  ThursdayEveThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/ThirdHour/PsalmAndGospel.json"),
  ThursdayEveThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/ThirdHour/copticProphecies.json"),
  ThursdayEveThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/ThirdHour/Prophecies.json"),
  //Sixth
  ThursdayEveSixthHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/SixthHour/mainPrayer.json"),
  ThursdayEveSixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/SixthHour/copticPsalmAndGospel.json"),
  ThursdayEveSixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/SixthHour/PsalmAndGospel.json"),
  ThursdayEveSixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/SixthHour/copticProphecies.json"),
  ThursdayEveSixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/SixthHour/Prophecies.json"),
  //NinthHour
  ThursdayEveNinthHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/NinthHour/mainPrayer.json"),
  ThursdayEveNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/NinthHour/copticPsalmAndGospel.json"),
  ThursdayEveNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/NinthHour/PsalmAndGospel.json"),
  ThursdayEveNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/NinthHour/copticProphecies.json"),
  ThursdayEveNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/NinthHour/Prophecies.json"),
  //Eleventh
  ThursdayEveEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/EleventhHour/mainPrayer.json"),
  ThursdayEveEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/EleventhHour/copticPsalmAndGospel.json"),
  ThursdayEveEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/EleventhHour/PsalmAndGospel.json"),
  ThursdayEveEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/EleventhHour/copticProphecies.json"),
  ThursdayEveEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Thursday/ThursdayEve/EleventhHour/Prophecies.json"),
  //FridayDay
  //FirstHour
  FridayDayFirstHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/FirstHour/mainPrayer.json"),
  FridayDayFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/FirstHour/copticPsalmAndGospel.json"),
  FridayDayFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/FirstHour/PsalmAndGospel.json"),
  FridayDayFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/FirstHour/copticProphecies.json"),
  FridayDayFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/FirstHour/Prophecies.json"),
  //ThirdHour
  FridayDayThirdHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/ThirdHour/mainPrayer.json"),
  FridayDayThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/ThirdHour/copticPsalmAndGospel.json"),
  FridayDayThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/ThirdHour/PsalmAndGospel.json"),
  FridayDayThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/ThirdHour/copticProphecies.json"),
  FridayDayThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/ThirdHour/Prophecies.json"),
  //Sixth
  FridayDaySixthHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/SixthHour/mainPrayer.json"),
  FridayDaySixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/SixthHour/copticPsalmAndGospel.json"),
  FridayDaySixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/SixthHour/PsalmAndGospel.json"),
  FridayDaySixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/SixthHour/copticProphecies.json"),
  FridayDaySixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/SixthHour/Prophecies.json"),
  FridayDaySixthHourcopticPaulineEpistle: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/SixthHour/copticPaulineEpistle.json"),
  FridayDaySixthHourPaulineEpistle: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/SixthHour/PaulineEpistle.json"),
  FridayDaySixthHourRightHandThief: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/SixthHour/RightHandThief.json"),
  //NinthHour
  FridayDayNinthHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/NinthHour/mainPrayer.json"),
  FridayDayNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/NinthHour/copticPsalmAndGospel.json"),
  FridayDayNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/NinthHour/PsalmAndGospel.json"),
  FridayDayNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/NinthHour/copticProphecies.json"),
  FridayDayNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/NinthHour/Prophecies.json"),
  FridayDayNinthHourcopticPaulineEpistle: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/NinthHour/copticPaulineEpistle.json"),
  FridayDayNinthHourPaulineEpistle: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/NinthHour/PaulineEpistle.json"),
  //Eleventh
  FridayDayEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/EleventhHour/mainPrayer.json"),
  FridayDayEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/EleventhHour/copticPsalmAndGospel.json"),
  FridayDayEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/EleventhHour/PsalmAndGospel.json"),
  FridayDayEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/EleventhHour/copticProphecies.json"),
  FridayDayEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/EleventhHour/Prophecies.json"),
  //Twelfth
  FridayDayTwelfthHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/TwelfthHour/mainPrayer.json"),
  FridayDayTwelfthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/TwelfthHour/copticPsalmAndGospel.json"),
  FridayDayTwelfthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/TwelfthHour/PsalmAndGospel.json"),
  FridayDayTwelfthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/TwelfthHour/copticProphecies.json"),
  FridayDayTwelfthHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayDay/TwelfthHour/Prophecies.json"),
  //FridayEve
  //FirstHour
  FridayEveFirstHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/FirstHour/mainPrayer.json"),
  FridayEveFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/FirstHour/copticPsalmAndGospel.json"),
  FridayEveFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/FirstHour/PsalmAndGospel.json"),
  FridayEveFirstHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/FirstHour/copticProphecies.json"),
  FridayEveFirstHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/FirstHour/Prophecies.json"),
  //ThirdHour
  FridayEveThirdHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/ThirdHour/mainPrayer.json"),
  FridayEveThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/ThirdHour/copticPsalmAndGospel.json"),
  FridayEveThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/ThirdHour/PsalmAndGospel.json"),
  FridayEveThirdHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/ThirdHour/copticProphecies.json"),
  FridayEveThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/ThirdHour/Prophecies.json"),
  //Sixth
  FridayEveSixthHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/SixthHour/mainPrayer.json"),
  FridayEveSixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/SixthHour/copticPsalmAndGospel.json"),
  FridayEveSixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/SixthHour/PsalmAndGospel.json"),
  FridayEveSixthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/SixthHour/copticProphecies.json"),
  FridayEveSixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/SixthHour/Prophecies.json"),
  //NinthHour
  FridayEveNinthHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/NinthHour/mainPrayer.json"),
  FridayEveNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/NinthHour/copticPsalmAndGospel.json"),
  FridayEveNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/NinthHour/PsalmAndGospel.json"),
  FridayEveNinthHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/NinthHour/copticProphecies.json"),
  FridayEveNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/NinthHour/Prophecies.json"),
  //Eleventh
  FridayEveEleventhHourMain: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/EleventhHour/mainPrayer.json"),
  FridayEveEleventhHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/EleventhHour/copticPsalmAndGospel.json"),
  FridayEveEleventhHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/EleventhHour/PsalmAndGospel.json"),
  FridayEveEleventhHourcopticProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/EleventhHour/copticProphecies.json"),
  FridayEveEleventhHourProphecies: require("../assets/json/books/booksTable/Pascha/Friday/FridayEve/EleventhHour/Prophecies.json"),
  //BrightSaturday
  //Praises
  BrightSaturdayPraisesMain: require("../assets/json/books/booksTable/Pascha/Saturday/Praises/mainPrayer.json"),
  //FirstHour
  BrightSaturdayFirstHourMain: require("../assets/json/books/booksTable/Pascha/Saturday/FirstHour/mainPrayer.json"),
  BrightSaturdayFirstHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/FirstHour/copticPsalmAndGospel.json"),
  BrightSaturdayFirstHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/FirstHour/PsalmAndGospel.json"),
  BrightSaturdayFirstHourcopticPauline: require("../assets/json/books/booksTable/Pascha/Saturday/FirstHour/copticPauline.json"),
  BrightSaturdayFirstHourPauline: require("../assets/json/books/booksTable/Pascha/Saturday/FirstHour/Pauline.json"),
  //ThirdHour
  BrightSaturdayThirdHourMain: require("../assets/json/books/booksTable/Pascha/Saturday/ThirdHour/mainPrayer.json"),
  BrightSaturdayThirdHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/ThirdHour/copticPsalmAndGospel.json"),
  BrightSaturdayThirdHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/ThirdHour/PsalmAndGospel.json"),
  BrightSaturdayThirdHourProphecies: require("../assets/json/books/booksTable/Pascha/Saturday/ThirdHour/Prophecies.json"),
  //Sixth
  BrightSaturdaySixthHourMain: require("../assets/json/books/booksTable/Pascha/Saturday/SixthHour/mainPrayer.json"),
  BrightSaturdaySixthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/SixthHour/copticPsalmAndGospel.json"),
  BrightSaturdaySixthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/SixthHour/PsalmAndGospel.json"),
  BrightSaturdaySixthHourProphecies: require("../assets/json/books/booksTable/Pascha/Saturday/SixthHour/Prophecies.json"),
  //Revelations
  BrightSaturdayRevelationsMain: require("../assets/json/books/booksTable/Pascha/Saturday/Revelations/mainPrayer.json"),
  //NinthHour
  BrightSaturdayNinthHourMain: require("../assets/json/books/booksTable/Pascha/Saturday/NinthHour/mainPrayer.json"),
  BrightSaturdayNinthHourcopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/NinthHour/copticPsalmAndGospel.json"),
  BrightSaturdayNinthHourPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/NinthHour/PsalmAndGospel.json"),
  BrightSaturdayNinthHourProphecies: require("../assets/json/books/booksTable/Pascha/Saturday/NinthHour/Prophecies.json"),
  //Liturgy
  offertoryBrightSaturday: require("../assets/json/books/booksTable/Pascha/Saturday/Liturgy/offertory.json"),
  liturgyOfWordBrightSaturday: require("../assets/json/books/booksTable/Pascha/Saturday/Liturgy/liturgyOfWord.json"),
  copticPaulineEpistleBrightSaturday: require("../assets/json/books/booksTable/Pascha/Saturday/Liturgy/copticPaulineEpistle.json"),
  chantedLiturgyPsalmBrightSaturday: require("../assets/json/books/booksTable/Pascha/Saturday/Liturgy/chantedLiturgyPsalm.json"),
  liturgyofStBasilBrightSaturday: require("../assets/json/books/booksTable/Pascha/Saturday/Liturgy/liturgyofStBasil.json"),
  liturgyofStGregoryBrightSaturday: require("../assets/json/books/booksTable/Pascha/Saturday/Liturgy/liturgyofStGregory.json"),
  //Communion
  BrightSaturdayCommunionMain: require("../assets/json/books/booksTable/Pascha/Saturday/Communion/mainPrayer.json"),
  BrightSaturdayCommunioncopticPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/Communion/copticPsalmAndGospel.json"),
  BrightSaturdayCommunionPsalmAndGospel: require("../assets/json/books/booksTable/Pascha/Saturday/Communion/PsalmAndGospel.json"),
  BrightSaturdayCommunionProphecies: require("../assets/json/books/booksTable/Pascha/Saturday/Communion/Prophecies.json"),
  //index
  versesofCymbalsIndex: require("../assets/json/books/booksTable/Index/versesofCymbals.json"),
  psalmResponsesIndex: require("../assets/json/books/booksTable/Index/psalmResponses.json"),
  gospelResponsesIndex: require("../assets/json/books/booksTable/Index/gospelResponses.json"),
  theotokiasIndex: require("../assets/json/books/booksTable/Index/theotokias.json"),
  papalIndex: require("../assets/json/books/booksTable/Index/papalHymns.json"),
  hitensIndex: require("../assets/json/books/booksTable/Index/HitensIndex.json"),
  actsResponseIndex: require("../assets/json/books/booksTable/Index/ActsResponseIndex.json"),
};

export default homescreenPaths;
