const images = {
  psalmody: require("../assets/images/david.jpg"),
  liturgy: require("../assets/images/censer.jpg"),
  pascha: require("../assets/images/holyweek.jpg"),
  veneration: require("../assets/images/mary.jpg"),
  index: require("../assets/images/indexpic.png"),
  vp: require("../assets/images/vp.jpg"),
  mp: require("../assets/images/mp.jpg"),
  abouticon: require("../assets/images/abouticon.png"),
  annuciation: require("../assets/images/annuciation.jpg"),
  brightsaturday: require("../assets/images/brightsaturday.jpg"),
  censer: require("../assets/images/censer.jpg"),
  coptic: require("../assets/images/coptic.png"),
  communion: require("../assets/images/communion.jpg"),
  paschathursday: require("../assets/images/covenantThursday.jpg"),
  paschafriday: require("../assets/images/crucifixion.jpg"),
  david: require("../assets/images/david.jpg"),
  faecebook: require("../assets/images/facebook.png"),
  paschamonday: require("../assets/images/figTree.jpg"),
  generalFuneral: require("../assets/images/generalFuneral.jpg"),
  headerborder: require("../assets/images/headerborder.png"),
  holyweek: require("../assets/images/holyweek.jpg"),
  homeicon: require("../assets/images/homeicon.png"),
  indexpic: require("../assets/images/indexpic.png"),
  instagram: require("../assets/images/instagram.png"),
  paschamondayeve: require("../assets/images/jesuskicksout.jpg"),
  paschatuesdayeve: require("../assets/images/jesusteaches.jpg"),
  paschafridayeve: require("../assets/images/Judasbetrays.jpg"),
  paschawednesday: require("../assets/images/judasselling.jpg"),
  lent: require("../assets/images/lent.jpg"),
  logofinal: require("../assets/images/logofinal.png"),
  mapicon: require("../assets/images/mapicon.png"),
  mary: require("../assets/images/mary.jpg"),
  paschaSunday: require("../assets/images/palmSunday.jpg"),
  paschatuesday: require("../assets/images/talents.jpg"),
  paschawednesdayeve: require("../assets/images/wisevirgins.jpg"),
  paschathursdayeve: require("../assets/images/womanperfume.jpg"),
  first: require("../assets/images/first.png"),
  third: require("../assets/images/third.png"),
  sixth: require("../assets/images/sixth.png"),
  ninth: require("../assets/images/ninth.png"),
  eleventh: require("../assets/images/eleventh.png"),
  twelfth: require("../assets/images/twelvth.png"),
};

export default images;
