const Languages = {
  eng: {
    about: "About Us",
    applanguage: "Application Language",
    applanguagedescription:
      "Set the language of the application to fit your preference.",

    arabic: "Arabic",
    arabicdescription: "Display the Arabic words in the Arabic Language",
    backgroundselector: "Select Background",
    backgroundselectordescription: "Set the Theme of the application",
    books: "Books",
    contents: "Contents",
    coptic: "Coptic",
    copticarabic: "Coptic-Arabic",
    copticarabicdescription: "Display the Coptic words in the Arabic Language",
    copticdescription: "Display the Coptic words in the Coptic Language",
    copticenglish: "Coptic-English",
    copticenglishdescription:
      "Display the Coptic words in the English Language",
    dark: "Dark Theme",
    displaylang: "Display Language",
    english: "English",
    englishdescription: "Display the English words in the English Language",
    Epep: "Epep",
    facebook: "Facebook Page",
    fullFeasts: "Calender",
    fontsizelabel: "Font Size: ",
    fontsizeselector: "Select Font Size",
    Hathor: "Hathor",
    home: "Home Page",
    instagram: "Instagram Page",
    Koiahk: "Koiahk",
    FIRST_SUNDAY_OF_KIAHK: "1st Sunday of the Month of Kiahk",
    SECOND_SUNDAY_OF_KIAHK: "2nd Sunday of the Month of Kiahk",
    THIRD_SUNDAY_OF_KIAHK: "3rd Sunday of the Month of Kiahk",
    FOURTH_SUNDAY_OF_KIAHK: "4th Sunday of the Month of Kiahk",
    language: "Language",
    noupdates: "No Updates",
    popeSelect: "Choose your Diocese",
    popeSelectDescription:
      "This feature allows you to add your Diocese Bishop/Metropolitan and it will auto populate all of their names in the neccessary order in the responses.",
    copticPope: "Coptic Pope: His Holiness Pope ",
    antiochPope: "Antioch Pope: Mar Ignatius",
    dioceseBishopMetropolitain: "Diocese Bishop/Metropolitan:",
    setBishop: "Set Diocese Bishop",
    BishopIsPresent: "Is a Bishop present?",
    moreThan3Bishops: "Are there more than 3 Bishops Present?",
    AddBishops: "Add Bishops",
    BishopsPresent: "Bishops Present",
    update: "Update Application",
    setCurrentDate: "Set Current Date",
    setYear: "Change Year",
    changeDate: "Change Date",
    languageselctor: "Language Selector",
    light: "Light Theme",
    menuBook: "Books",
    menuContents: "Contents",
    Meshir: "Meshir",
    Mesore: "Mesore",
    Nesi: "Nesi",
    notes: "Notes Page",
    Paone: "Paone",
    Paope: "Paope",
    Paremhotep: "Paremhotep",
    Parmoute: "Parmoute",
    Pashons: "Pashons",
    purchase: "Purchase Book",
    redeem: "Redeem Code",
    restore: "Restore Purchases",
    settings: "Settings",
    TableOfContents: "Table of Contents",

    share: "Share Application",
    Thoout: "Thoout",
    Tobe: "Tobe",
    todayprayer: "Today's Prayer",
    presentationMode: "Presentation Mode",
    presentationModeDescription:
      "Enable Pagination which allows you to scroll one page at a time.",
    setTimeTodayPrayer:
      "Set the time where you would like to roll over to the next day.",
    versesofCymbals: "Verses of Cymbals",
    doxologies: "Doxologies",
    actsResponse: "Acts Response",
    gospelResponse: "Gospel Response",
    intercessions: "Intercessions (Hitens)",
    saintsMenu: "Saints Menu",
    commentsOrQuestions: "Comment/Question",
    todayprayerdescription:
      "Today's Prayer options allows the application to automatically load the prayers/hymns said today rather than loading all the possible options",
    NATIVITY: "Nativity",
    EPIPHANY: "Theophany Feast",
    EPIPHANY_SECONDDAY: "2nd Day of Theophany Feast",
    NATIVITY_SECONDDAY: "2nd Day of Nativity Feast",
    ANNUNCIATION: "Annunciation Feast",
    RESURRECTION: "Resurrection",
    PALM_SUNDAY: "Palm Sunday Feast",
    ASCENSION: "Ascension Feast",
    ASCENSIONTOPENTECOST: "Period from Ascnesion to Pentecost",
    PENTECOST: "Pentecost Feast",
    FEAST_OF_CIRCUMCISION: "Feast of the Circumcision",
    ENTRY_EGYPT: "Entrance of the Lord Christ into the Land of Egypt Feast",
    WEDDING_CANA: "Wedding at Cana of Galilee Feast",
    PRESENTATION_TEMPLE: "Presentation of the Lord Christ in the Temple",
    TRANSFIGURATION: "Transfiguration Feast",
    COVENANT_THURSDAY: "Convenant Thursday Feast",
    THOMAS_SUNDAY: "Thomas Sunday Feast",
    ASSUMPTION_STMARY: "Assumption of St. Mary",
    FEAST_OF_APOSTLES: "Feast of the Apostles",
    COPTIC_NEW_YEAR: "Coptic New Year",
    FEAST_OF_CROSS: "Feast of the Cross",
    FEAST_OF_CROSS_3: "Feast of the Cross (3 days)",
    GREAT_LENT: "Great Lent",
    HOLY_WEEK: "Holy Week",
    FAST_OF_APOSTLES: "Fast of the Apostles",
    FAST_STMARY: "Fast of St. Mary",
    NATIVITY_FAST: "The Holy Nativity Fast",
    GOOD_FRIDAY: "Good Friday",
    LAZARUS_SATURDAY: "Lazarus Saturday",
    JONAH_FEAST: "Jonah's Feast",
    JONAH_FAST: "Jonah's Fast",
    HOLY_50: "Holy 50 Days (Pentecostal)",
    NATIVITY_PARAMOUN: "Nativity Paramoun",
    EPIPHANY_PARAMOUN: "Theophany Paramoun",
    NATIVITY_PERIOD: "Nativity Period",
    week_of: "Week of the",
    ARCHANGEL_MICHAEL: "Archangel Michael",
    ARCHANGEL_GABRIEL: "Archangel Gabriel",
    JOHN_THE_BAPTIST: "St.John The Baptist",
    ST_MARK: "St.Mark the Apostle",
    ST_STEPHEN: "St.Stephen the Archdeacon",
    ST_GEORGE: "St.George",
    ST_PHILOPATER: "St.Philopatir",
    ST_MINA: "St.Mina",
    ST_ABANOUB: "St.Abanoub",
    ST_DEMIANA: "St.Demiana",
    ST_MARINA: "St.Marina",
    ST_ANTHONY: "St.Anthony",
    ST_PAULHERMIT: "St.Paul the Hermit",
    ST_MOSES: "St.Moses",
    ST_PISHOI: "St.Pishoy",
    ST_REWIS: "St.Rewis",
    ST_JOHN_THE_SHORT: "St.John the Short",
    ST_KARAS: "St.Karas",
    ST_KIROLLOS_SIXTH: "Pope Kirollos the 6th",
  },
  ara: {
    about: "معلومات",
    applanguage: "لغة التطبيق",
    applanguagedescription: "اضبط لغة التطبيق بما يناسبك.",
    arabic: "عربي",
    arabicdescription: "عرض الكلمات العربية باللغة العربية",
    backgroundselector: "اختار الخلفية",
    backgroundselectordescription: "قم بتعيين خلفية التطبيق ",

    books: "الكتب",
    contents: "المحتويات",
    coptic: "قبطي",
    copticarabic: "قبطي معرب",
    copticarabicdescription: "عرض الكلمات القبطية باللغة العربية",
    copticdescription: "عرض الكلمات القبطية باللغة القبطية",
    copticenglish: "قبطي إنجليزي",
    copticenglishdescription: "عرض الكلمات القبطية باللغة الإنجليزية",
    dark: "خلفية غامقة ",
    displaylang: "عرض اللغة",
    english: "إنجليزي",
    englishdescription: "عرض الكلمات الإنجليزية باللغة الإنجليزية",
    Epep: "أبيب",
    facebook: "صفحة الفيسبوك",
    fullFeasts: "تقويم الأعياد / الصوم",
    popeSelect: "اختار أبرشيتك",
    popeSelectDescription:
      "تسمح لك هذه الميزة بإضافة أسقف الأبرشية / المطران الخاص بك وسوف تقوم تلقائيًا بملء جميع أسمائهم بالترتيب الضروري في المردات و الألحان.",
    copticPope: "بابا الأقباط: قداسة البابا المعظم الانبا ",
    antiochPope: "بابا انطاكية: مار إغناطيوس",
    dioceseBishopMetropolitain: "اسقف\\مطران الأبروشية",
    setBishop: "إختار أسقف الإبرشية ",
    fontsizelabel: "حجم الخط:",
    fontsizeselector: "حدد حجم الخط",
    Hathor: "هاتور",
    home: "الصفحة الرئيسية",
    instagram: "صفحة الإنستاجرام",
    Koiahk: "كيهك",
    language: "اللغة",
    languageselctor: "حدد اللغة",
    light: "خلفية فتحية",
    menuBook: "كتب",
    menuContents: "المحتويات",
    Meshir: "امشير",
    Mesore: "مسرى",
    Nesi: "نسيئ",
    notes: "صفحة الملاحظات",
    Paone: "بؤنة",
    Paope: "بابه",
    Paremhotep: "برمهات",
    Parmoute: "برموده",
    Pashons: "بشنس",
    purchase: "شراء الكتاب",
    redeem: "استرداد الشفرة",
    restore: "استعادة المشتريات",
    settings: "إعدادات",
    share: "مشاركة التطبيق",
    saintsMenu: "قائمة القديسين",
    versesofCymbals: "ارباع الناقوس",
    doxologies: "الذكصولوجيات",
    actsResponse: " مرد الأبركسيس",
    gospelResponse: " مرد الانجيل",
    intercessions: "الهيتينيات",
    commentsOrQuestions: "تعليق / سؤال",
    Thoout: "توت",
    Tobe: "طوبه",
    todayprayer: "صلاة اليوم",
    presentationMode: "صفحة ",
    presentationModeDescription:
      "تمكين ترقيم الصفحات الذي يسمح لك بتمرير صفحة واحدة في كل مرة.",
    BishopIsPresent: "هل الأسقف حاضر؟",
    moreThan3Bishops: "هل يوجد أكثر من 3 أساقفة حاضرين؟",
    BishopsPresent: "الأساقفة الحاضرون",
    TableOfContents: " المحتويات",
    setTimeTodayPrayer:
      "اضبط الوقت الذي ترغب في الانتقال فيه إلى اليوم التالي.",
    update: "تحديث التطبيق",
    noupdates: "لا توجد تحديثات",
    setCurrentDate: "حدد التاريخ الحالي",
    setYear: "حدد السنة",
    changeDate: "حدد التاريخ",
    todayprayerdescription:
      "تتيح خيارات الصلاة اليوم للتطبيق تحميل الصلوات / الالحان التي تقال اليوم تلقائيًا بدلاً من تحميل جميع الخيارات الممكنة",
    FIRST_SUNDAY_OF_KIAHK: "الأسبوع الاول من شهر كيهك",
    SECOND_SUNDAY_OF_KIAHK: "الأسبوع الثاني من شهر كيهك",
    THIRD_SUNDAY_OF_KIAHK: "الأسبوع الثالث من شهر كيهك",
    FOURTH_SUNDAY_OF_KIAHK: "الأسبوع الرابع من شهر كيهك",
    NATIVITY: "عيد الميلاد",
    EPIPHANY: "عيد الغطاس",
    EPIPHANY_SECONDDAY: "ثاني يوم عيد الغطاس",
    NATIVITY_SECONDDAY: "ثاني يوم عيد الميلاد",
    AddBishops: "أضف الأساقفة",
    ANNUNCIATION: "عيد البشارة",
    RESURRECTION: "عيد القيامة",
    PALM_SUNDAY: "احد الشعانين",
    ASCENSION: "عيد الصعود",
    ASCENSIONTOPENTECOST: "الفترة من الصعود إلى عيد العنصرة",
    PENTECOST: "عيد العنصرة",
    FEAST_OF_CIRCUMCISION: "عيد الختان",
    ENTRY_EGYPT: "عيد دخول المسيح ارض مصر",
    WEDDING_CANA: "عيد عرس قانا الجليل",
    PRESENTATION_TEMPLE: "عيد دخول المسيح",
    TRANSFIGURATION: "عيد التجلي",
    COVENANT_THURSDAY: "خميس العهد",
    THOMAS_SUNDAY: "احد توما",
    ASSUMPTION_STMARY: "عيد العذراء",
    FEAST_OF_APOSTLES: "عيد الرسل",
    COPTIC_NEW_YEAR: "عيد النيروز",
    FEAST_OF_CROSS: "عيد الصليب",
    FEAST_OF_CROSS_3: "عيد الصليب (3)",
    GREAT_LENT: "الصوم الكبير",
    HOLY_WEEK: " اسبوع الالام",
    FAST_OF_APOSTLES: "صوم الرسل",
    FAST_STMARY: "صوم العذراء",
    NATIVITY_FAST: "صوم الميلاد",
    GOOD_FRIDAY: "الجمعة العظيمة",
    LAZARUS_SATURDAY: "سبت لعازر",
    JONAH_FEAST: "فصح يونان",
    JONAH_FAST: "صوم يونان",
    HOLY_50: "الخماسين المقدس",
    NATIVITY_PARAMOUN: "برمون الميلاد",
    EPIPHANY_PARAMOUN: "برمون الغطاس",
    NATIVITY_PERIOD: "بين عيد الميلاد و الختان",
    week_of: "الإسبوع ال",
    ARCHANGEL_MICHAEL: "الملاك ميخائيل",
    ARCHANGEL_GABRIEL: "الملاك غبريال",
    JOHN_THE_BAPTIST: "يوحنا المعمدان",
    ST_MARK: "مارمرقس الرسول",
    ST_STEPHEN: "الشهيد استفانوس",
    ST_GEORGE: "الشهيد مارجرجس",
    ST_PHILOPATER: "الشهيد مرقوريوس",
    ST_MINA: "الشهيد مارمينا",
    ST_ABANOUB: "الشهيد ابانوب",
    ST_DEMIANA: "الشهيدة دميانه",
    ST_MARINA: "الشهيدة مارينا",
    ST_ANTHONY: "الأنبا أنطونيوس",
    ST_PAULHERMIT: "الأنبا بولا",
    ST_MOSES: "الأنبا موسى",
    ST_PISHOI: "الأنبا بيشوي",
    ST_REWIS: "الأنبا رويس",
    ST_KARAS: "الأنبا كاراس",
    ST_JOHN_THE_SHORT: "الأنبا يوحنا القصير",
    ST_KIROLLOS_SIXTH: "البابا كيرلس",
  },
};

export default Languages;
