const Languages = {
  eng: {
    about: "About Us",
    applanguage: "Application Language",
    arabic: "Arabic",
    arabicdescription: "Display the Arabic words in the Arabic Language",
    backgroundselector: "Select Background",
    books: "Books",
    contents: "Contents",
    coptic: "Coptic",
    copticarabic: "Coptic-Arabic",
    copticarabicdescription: "Display the Coptic words in the Arabic Language",
    copticdescription: "Display the Coptic words in the Coptic Language",
    copticenglish: "Coptic-English",
    cocopticenglishdescriptionptic:
      "Display the Coptic words in the English Language",
    dark: "Dark Theme",
    displaylang: "Display Language",
    english: "English",
    englishdescription: "Display the English words in the English Language",
    Epip: "Epip",
    facebook: "Facebook Page",
    fontsizelabel: "Font Size: ",
    fontsizeselector: "Select Font Size",
    Hatoor: "Hatoor",
    home: "Home Page",
    instagram: "Instagram Page",
    Kiahk: "Kiahk",
    language: "Language",
    languageselctor: "Language Selector",
    light: "Light Theme",
    menuBook: "Books",
    menuContents: "Contents",
    Meshir: "Meshir",
    Mesori: "Mesori",
    Nesi: "Nesi",
    notes: "Notes Page",
    Paoni: "Paoni",
    Paopi: "Paopi",
    Paremhat: "Paremhat",
    Parmouti: "Parmouti",
    Pashons: "Pashons",
    purchase: "Purchase Book",
    redeem: "Redeem Code",
    restore: "Restore Purchases",
    settings: "Settings",
    share: "Share Application",
    Thout: "Thout",
    Tobe: "Tobe",
    todayprayer: "Today's Prayer",
  },
  ara: {
    about: "معلومات",
    applanguage: "لغة التطبيق",
    arabic: "عربي",
    arabicdescription: "عرض الكلمات العربية باللغة العربية",
    backgroundselector: "اختار الخلفية",
    books: "الكتب",
    contents: "المحتويات",
    coptic: "قبطي",
    copticarabic: "قبطي معرب",
    copticarabicdescription: "عرض الكلمات القبطية باللغة العربية",
    copticdescription: "عرض الكلمات القبطية باللغة القبطية",
    copticenglish: "قبطي إنجليزي",
    cocopticenglishdescriptionptic: "عرض الكلمات القبطية باللغة الإنجليزية",
    dark: "خلفية غمئة",
    displaylang: "عرض اللغة",
    english: "إنجليزي",
    englishdescription: "عرض الكلمات الإنجليزية باللغة الإنجليزية",
    Epip: "أبيب",
    facebook: "صفحة الفيسبوك",
    fontsizelabel: "حجم الخط:",
    fontsizeselector: "حدد حجم الخط",
    Hatoor: "هاتور",
    home: "الصفحة الرئيسية",
    instagram: "صفحة الإنستاجرام",
    Kiahk: "كيهك",
    language: "اللغة",
    languageselctor: "حدد اللغة",
    light: "خلفية فتحية",
    menuBook: "كتب",
    menuContents: "المحتويات",
    Meshir: "امشير",
    Mesori: "مسرى",
    Nesi: "نسيئ",
    notes: "صفحة الملاحظات",
    Paoni: "بؤنة",
    Paopi: "بابه",
    Paremhat: "برمهات",
    Parmouti: "برموده",
    Pashons: "بشنس",
    purchase: "شراء الكتاب",
    redeem: "استرداد الشفرة",
    restore: "استعادة المشتريات",
    settings: "إعدادات",
    share: "مشاركة التطبيق",
    Thout: "توت",
    Tobe: "طوبه",
    todayprayer: "صلاة اليوم",
  },
};

export default Languages;
