const Languages = {
  eng: {
    about: "About Us",
    applanguage: "Application Language",
    applanguagedescription:
      "Set the language of the application to fit your preference.",
    onboardingScreen: "Onboarding Screen",

    arabic: "Arabic",
    arabicdescription: "Display the Arabic words in the Arabic Language",
    backgroundselector: "Select Background",
    backgroundselectordescription: "Set the Theme of the application",
    books: "Books",
    contents: "Contents",
    coptic: "Coptic",
    arabicengishMelodies: "Arabic-English (Melodies)",
    copticarabic: "Coptic-Arabic",
    arabicengishMelodiesdescription:
      "Display the Arabic words within the melodies in English",
    copticarabicdescription: "Display the Coptic words in the Arabic Language",
    copticdescription: "Display the Coptic words in the Coptic Language",
    copticenglish: "Coptic-English",
    copticenglishdescription:
      "Display the Coptic words in the English Language",
    dark: "Dark Theme",
    displaylang: "Display Language",
    english: "English",
    englishdescription: "Display the English words in the English Language",
    Epep: "Epep",
    facebook: "Facebook Page",
    fullFeasts: "Calendar",
    searchPage: "Search Page",
    fontsizelabel: "Font Size: ",
    fontsizeselector: "Select Font Size",
    Hathor: "Hathor",
    home: "Home Page",
    instagram: "Instagram Page",
    Koiahk: "Koiahk",
    FIRST_SUNDAY_OF_KIAHK: "1st Sunday of the Month of Kiahk",
    SECOND_SUNDAY_OF_KIAHK: "2nd Sunday of the Month of Kiahk",
    THIRD_SUNDAY_OF_KIAHK: "3rd Sunday of the Month of Kiahk",
    FOURTH_SUNDAY_OF_KIAHK: "4th Sunday of the Month of Kiahk",
    language: "Language",
    noupdates: "No Updates",
    popeSelect: "Choose your Diocese",
    popeSelectDescription:
      "This feature allows you to add your Diocese Bishop/Metropolitan and it will auto populate all of their names in the neccessary order in the responses.",
    copticPope: "Coptic Pope: His Holiness Pope ",
    antiochPope: "Antioch Pope: Mar Ignatius",
    dioceseBishopMetropolitain: "Diocese Bishop/Metropolitan:",
    setBishop: "Set Diocese Bishop",
    BishopIsPresent: "Is a Bishop present?",
    moreThan3Bishops: "Are there more than 3 Bishops Present?",
    AddBishops: "Add Bishops",
    BishopsPresent: "Bishops Present",
    update: "Update Application",
    setCurrentDate: "Set Current Date",
    setYear: "Change Year",
    changeDate: "Change Date",
    languageselctor: "Language Selector",
    light: "Light Theme",
    menuBook: "Books",
    menuContents: "Contents",
    Meshir: "Meshir",
    Mesore: "Mesore",
    Nesi: "Nesi",
    notes: "Notes Page",
    Paone: "Paone",
    Paope: "Paope",
    Paremhotep: "Paremhotep",
    Parmoute: "Parmoute",
    Pashons: "Pashons",
    purchase: "Purchase Book",
    redeem: "Redeem Code",
    restore: "Restore Purchases",
    settings: "Settings",
    TableOfContents: "Table of Contents",

    share: "Share Application",
    Thoout: "Thoout",
    Tobe: "Tobe",
    todayprayer: "Today's Prayer",
    presentationMode: "Presentation Mode",
    presentationModeDescription:
      "Enable Pagination which allows you to scroll one page at a time.",
    NotificationPermission: "Enable Notifications",
    NotificationPermissionDescription:
      "Enable Notifications to allow for 7 Tunes to send you Notifications of saint's feasts and occasions.",
    setTimeTodayPrayer:
      "Set the time where you would like to roll over to the next day.",
    versesofCymbals: "Verses of Cymbals",
    doxologies: "Doxologies",
    actsResponse: "Acts Response",
    gospelResponse: "Gospel Response",
    pioik: "The Hymn Pi-Oik",
    intercessions: "Intercessions (Hitens)",
    saintsMenu: "Saints Menu",
    commentsOrQuestions: "Comment/Question",
    todayprayerdescription:
      "Today's Prayer options allows the application to automatically load the prayers/hymns said today rather than loading all the possible options",
    NATIVITY: "Nativity Feast",
    NATIVITY_FACT:
      "The Nativity of Christ (Nativity) on Kayhk 29, c. January 7: It is preceded by a fast of 43 days. Its aim is to confirm the divine love, when God sent His Only – begotten Son incarnate. Thus, He restored to humanity her honor, and sanctified our daily life, offering His life as a Sacrifice on our behalf.",
    EPIPHANY: "Theophany Feast",
    EPIPHANY_FACT:
      "The Epiphany or the Baptism of Christ on Tobah 11, c. January 19: It is connected with Nativity and the circumcision feasts. For on Nativity, the Word of God took what is ours (our humanity) and in the “circumcision” He subjected Himself to the Law as He became one of us, but in the Epiphany He offered us what is His own. By His incarnation He became a true man while He still being the Only-begotten Son of God, and by baptism we became children of God in Him while we are human being In this feast, the liturgy of blessing the water is conducted, and the priest blesses the people by the water on their foreheads and hands to commemorate baptism.",
    EPIPHANY_SECONDDAY: "2nd Day of Theophany Feast",
    NATIVITY_SECONDDAY: "2nd Day of Nativity Feast",
    ANNUNCIATION: "Annunciation Feast",
    ANNUNCIATION_FACT:
      "The Annunciation (Baramhat 29, c. April 7): In it we recall the fulfillment of the Old Testament prophecies, and the attainment which the men of God had longed for across the ages, namely the coming of the Word of God incarnated in the Virgin’s womb (Matt. 13:17).",
    RESURRECTION: "Resurrection",
    RESURRECTION_FACT:
      "It is preceded by Great Lent (55 days) and is considered by the Coptic Church as the Feast.” Its delight continues for fifty days until the Pentecost. Resurrection is also essentially celebrated on every Sunday by participating A sacrament of the Eucharist. For the church wishes that all believers may enjoy the new risen life in Jesus Christ (Rom. 6:4).",
    PALM_SUNDAY: "Palm Sunday Feast",
    PALM_SUNDAY_FACT:
      "It is the Sunday which precedes Resurrection. It has its characteristic joyful hymns (the Shannon – Hosanna (Matt. 21:9), and its delightful rite. The church commemorates the entrance of our Lord Jesus into our inward Jerusalem to establish His Kingdom in us and gather all in Him. Therefore a delighful is procession or the redeemed believers, starts -God’s plan for Christ’s self-oblation. The procession moves towards the nave of the church were it stands before the icons of St. Mary, the Archangels, St. John the Baptist, the Apostles, the marthe ascetics etc… and before the church doors and the baptismal basin, praising God who embraces all together in His Son Jesus Christ. The procession ends by re-entering the sanctuary, for the of God of the Old and New testaments meet with the heavenly in heaven (sanctuary) forever. The end of the liturgy of Eucharist, a general funeral service is held over water, which is sprinkled on behalf of anyone who may die during the Holy week, since the regular funeral prayers are not conducted during this week. By this rite, the church stresses on her pre-occupation with the passion and crucifixion of Christ only. She itrates on the marvelous events of this unique week with its glorious readings and rites which concern our salvation.",
    ASCENSION: "Ascension Feast",
    ASCENSION_FACT:
      " It is celebrated on the fortieth day after Resurrection Is on a Thursday. In this feast we recall Him who raises and lifts us up to sit with Him in heaven (Eph. 2:6).",
    ASCENSIONTOPENTECOST: "Period from Ascnesion to Pentecost",
    PENTECOST: "Pentecost Feast",
    PENTECOST_FACT:
      "It represents the birthday of the Christian Church. Only-begotten Son paid the price for her salvation, He ascended heaven to prepare a place for her. He sent His Holy Spirit in her, offering her existence, guidance, sanctification and adornment as the Heavenly Bride. In this feast, the church chants hymns, being joyful with the resurrection of Christ, His ascension and the dwelling of His Holy Spirit in her, thus she connects the three feasts in one whole unity. On this day, the church conducts three sets of prayers, called “Kneeling,” during which incense and prayers are offered on behalf of the sick, the travelers, the winds, and it gives special attention to the dormant, as a sign of her enjoying the communion and unity with Christ that challenges even death.",
    FEAST_OF_CIRCUMCISION: "Feast of the Circumcision",
    FEAST_OF_CIRCUMCISION_FACT:
      " It is celebrated on the eighth day after Nativity (Tobah 6, c. 14 January), by which we remember that the Word of God who gave us the Law, He Himself was subjected to this Law, fulfilling it, to grant us the power to fulfill the Law in a spiritual manner. Thus we enjoy the circumcision of spirit and that of heart (Col. 2:11), instead of the literal circumcision of the flesh.",
    ENTRY_EGYPT: "Entrance of the Lord Christ into the Land of Egypt Feast",
    ENTRY_EGYPT_FACT:
      "The Coptic Church is distinguished among all nations with this unique divine work, by the coming of our Lord to Egypt among the Gentiles.",
    WEDDING_CANA: "Wedding at Cana of Galilee Feast",
    WEDDING_CANA_FACT:
      "Our Lord changed the water into wine, as His first miracle, at the wedding in Cana of Galilee, confirming His eagerness for our attaining the heavenly wedding, and granting us the wine of His exceeding love.",
    PRESENTATION_TEMPLE: "Presentation of the Lord Christ in the Temple",
    PRESENTATION_TEMPLE_FACT:
      "We remember that the Word of God became man and does not want us to be careless about our lives, but to set our goals early since childhood. Thus we have to work and fulfill our goals regardless of people related to us, in spite of our love and obedience to them (Luke 2:24).",
    TRANSFIGURATION: "Transfiguration Feast",
    TRANSFIGURATION_FACT:
      "The unity of the two testaments was manifested in this feast, for Moses and Elijah assembled together with Peter, James and John. The glory of our Lord was revealed to satisfy every soul who rises up with Him to the mountain of Tabor to enjoy the brightness of His Glory.",
    COVENANT_THURSDAY: "Covenant Thursday Feast",
    COVENANT_THURSDAY_FACT:
      "This is the Thursday of the Holy week. In it we commemorate the establishment of the Sacrament of Eucharist by our Lord Jesus, when He offered His Body and Blood as the living and effective Sacrifice, capable of sanctifying our hearts, granting us the victorious and eternal life. This is the only day of the Holy Week in which Sacrifice of the Eucharist is offered, and the rite of washing the feet is practiced in commemoration of what Christ did for His disciples. On this day also an unusual procession takes place, starting from the south of the church nave, during which a hymn of rebuking Jude the betrayal is chanted as a warning to us not to fall like him.",
    THOMAS_SUNDAY: "Thomas Sunday Feast",
    THOMAS_SUNDAY_FACT:
      "This is the Sunday that follows Resurrection; In it we bless those who believe without seeing so that all might live in faith through the internal touch of the Savior’s wounds (John 20:29).",
    ASSUMPTION_STMARY: "Assumption of St. Mary",
    FEAST_OF_APOSTLES: "Feast of the Apostles",
    FEAST_OF_APOSTLES_FACT:
      "This is the feast of martyrdom of the Apostles SS. Peter and Paul. It is preceded by a fasting period which starts on the day following the Pentecost. In this feast, the liturgy of blessing the water takes place, in which the priest washes the feet of his people (men and children) commemorating what the Lord did for His disciples. Thus, the priest remembers that he is a servant who washes the feet of the people of God and not a man of authority.",
    COPTIC_NEW_YEAR: "Coptic New Year",
    COPTIC_NEW_YEAR_FACT:
      "The word “Nayrouz” is Persian, meaning “the beginning of the year.” The Egyptian calendar goes back to 4240 B.C. Copts restored the calendar with the beginning of Diocletian’s reign in A.D 284, to commemorate the millions of Coptic martyrs. His reign is considered a golden era in which the church offered true witnesses to Christ, when the souls of martyrs departed to paradise and kept shining as living stars therein. This feast, with its joyful hymns, continues until the feast of the Cross (Tout 17, c. 27 September). Thus the church announces her joy and gladness with the martyrs through bearing the cross of our Lord Jesus Christ. In other words, the sufferings and martyrdom were turned into a source of joy.",
    FEAST_OF_CROSS: "Feast of the Cross",
    FEAST_OF_CROSS_FACT:
      "The second feast, is on Barmahat 10 (c. March 19) and commemorates the discovery of the Holy Cross on the hands of Queen Helen and King Constantine in A.D 326. During these two feasts the church conducts a procession similar to that of Palm-Sunday and uses the same tone in chanting (Shannon-Hosanna), to announce that the cause of her joy with the Cross is the openness of the hearts (the inner Jerusalem) to receive the Savior as the King who reigns within us.",
    FEAST_OF_CROSS_3: "Feast of the Cross (3 days)",
    FEAST_OF_CROSS_3_FACT:
      "The first feast is on Tout 17, (c. September 27). It commemorates the dedication of the Church of the Holy Cross which was built by Queen Helen, the mother of Emperor Constantine. During these two feasts the church conducts a procession similar to that of Palm-Sunday and uses the same tone in chanting (Shannon-Hosanna), to announce that the cause of her joy with the Cross is the openness of the hearts (the inner Jerusalem) to receive the Savior as the King who reigns within us.",
    GREAT_LENT: "Great Lent",
    HOLY_WEEK: "Holy Week",
    FAST_OF_APOSTLES: "Fast of the Apostles",
    FAST_STMARY: "Fast of St. Mary",
    NATIVITY_FAST: "The Holy Nativity Fast",
    GOOD_FRIDAY: "Good Friday",
    LAZARUS_SATURDAY: "Lazarus Saturday",
    JONAH_FEAST: "Jonah's Feast",
    JONAH_FAST: "Jonah's Fast",
    HOLY_50: "Holy 50 Days (Pentecostal)",
    NATIVITY_PARAMOUN: "Nativity Paramoun",
    EPIPHANY_PARAMOUN: "Theophany Paramoun",
    NATIVITY_PERIOD: "Nativity Period",
    week_of: "Week of the",
    ST_MARY: "St.Mary the Theotokos",
    ARCHANGEL_MICHAEL: "Archangel Michael",
    ARCHANGEL_GABRIEL: "Archangel Gabriel",
    ARCHANGEL_RAPHAEL: "Archangel Raphael",
    FOUR_INCORPOREAL_CREATURES: "The Four Incorporeal Living Creatures",
    TWENTY_FOUR_PRIESTS: "The Twenty Four Priests",
    JOHN_THE_BAPTIST: "St.John The Baptist",
    ST_MARK: "St.Mark the Apostle",
    ST_JOHN_BELOVED: "St.John the Beloved",
    ST_STEPHEN: "St.Stephen the Archdeacon",
    ST_GEORGE: "St.George",
    ST_PHILOPATER: "St.Philopatir",
    ST_MINA: "St.Mina",
    ST_THEODORE_SHOTEP: "St.Theodore of Shotep",
    ST_ABANOUB: "St.Abanoub",
    APAKIR_AND_JOHN: "St.Apakir and John his Brother",
    COSMAN_AND_DEMIAN: "Cosman and Demian",
    ST_DEMIANA: "St.Demiana",
    ST_MARINA: "St.Marina",
    ST_BARBARA: "St.Barbara",
    ST_JULIANA: "St.Juliana",
    ST_ANTHONY: "St.Anthony",
    ST_PAULHERMIT: "St.Paul the Hermit",
    MACARIUS_GREAT: "St.Macarius the Great",
    ATHANASIUS_APOSTOLIC: "St.Athansius the Apostolic",
    MAXIMUS_DOMETIUS: "St.Maximus and St.Dometius",
    ST_PACHOMIOUS: "St.Pachom ",
    ST_SHENOUDA_ARCHMANDRITE: "St.Shenouda the Archimanidrite",
    SAMUEL_CONFESSOR: "St.Samuel the Confessor",
    ST_MOSES: "St.Moses",
    ST_PISHOI: "St.Pishoy",
    ST_REWIS: "St.Rewis",
    ST_JOHN_THE_SHORT: "St.John the Short",
    ST_KARAS: "St.Karas",
    ST_KIROLLOS_SIXTH: "Pope Kirollos the 6th",
  },
  ara: {
    searchPage: "صفحة البحث",
    onboardingScreen: "شاشة التعليمات",
    about: "معلومات",
    applanguage: "لغة التطبيق",
    applanguagedescription: "اضبط لغة التطبيق بما يناسبك.",
    arabic: "عربي",
    arabicdescription: "عرض الكلمات العربية باللغة العربية",
    backgroundselector: "اختار الخلفية",
    backgroundselectordescription: "قم بتعيين خلفية التطبيق ",

    books: "الكتب",
    contents: "المحتويات",
    coptic: "قبطي",
    arabicengishMelodiesdescriptionarabic: "عربي فرنكو",
    copticarabic: "قبطي معرب",
    arabicengishMelodiesdescriptiondescription:
      "عرض الكلمات العربية باللغة الإنجليزية",
    copticarabicdescription: "عرض الكلمات القبطية باللغة العربية",
    copticdescription: "عرض الكلمات القبطية باللغة القبطية",
    copticenglish: "قبطي إنجليزي",
    copticenglishdescription: "عرض الكلمات القبطية باللغة الإنجليزية",
    dark: "خلفية غامقة ",
    displaylang: "عرض اللغة",
    english: "إنجليزي",
    englishdescription: "عرض الكلمات الإنجليزية باللغة الإنجليزية",
    Epep: "أبيب",
    facebook: "صفحة الفيسبوك",
    fullFeasts: "تقويم الأعياد / الصوم",
    popeSelect: "اختار أبرشيتك",
    popeSelectDescription:
      "تسمح لك هذه الميزة بإضافة أسقف الأبرشية / المطران الخاص بك وسوف تقوم تلقائيًا بملء جميع أسمائهم بالترتيب الضروري في المردات و الألحان.",
    copticPope: "بابا الأقباط: قداسة البابا المعظم الانبا ",
    antiochPope: "بابا انطاكية: مار إغناطيوس",
    dioceseBishopMetropolitain: "اسقف\\مطران الأبروشية",
    setBishop: "إختار أسقف الإبرشية ",
    fontsizelabel: "حجم الخط:",
    fontsizeselector: "حدد حجم الخط",
    Hathor: "هاتور",
    home: "الصفحة الرئيسية",
    instagram: "صفحة الإنستاجرام",
    Koiahk: "كيهك",
    language: "اللغة",
    languageselctor: "حدد اللغة",
    light: "خلفية فتحية",
    menuBook: "كتب",
    menuContents: "المحتويات",
    Meshir: "امشير",
    Mesore: "مسرى",
    Nesi: "نسيئ",
    notes: "صفحة الملاحظات",
    Paone: "بؤنة",
    Paope: "بابه",
    Paremhotep: "برمهات",
    Parmoute: "برموده",
    Pashons: "بشنس",
    purchase: "شراء الكتاب",
    redeem: "استرداد الشفرة",
    restore: "استعادة المشتريات",
    settings: "إعدادات",
    share: "مشاركة التطبيق",
    saintsMenu: "قائمة القديسين",
    versesofCymbals: "ارباع الناقوس",
    doxologies: "الذكصولوجيات",
    actsResponse: " مرد الأبركسيس",
    gospelResponse: " مرد الانجيل",
    intercessions: "الهيتينيات",
    commentsOrQuestions: "تعليق / سؤال",
    Thoout: "توت",
    Tobe: "طوبه",
    todayprayer: "صلاة اليوم",
    presentationMode: "صفحة ",
    presentationModeDescription:
      "تمكين ترقيم الصفحات الذي يسمح لك بتمرير صفحة واحدة في كل مرة.",
    BishopIsPresent: "هل الأسقف حاضر؟",
    moreThan3Bishops: "هل يوجد أكثر من 3 أساقفة حاضرين؟",
    BishopsPresent: "الأساقفة الحاضرون",
    TableOfContents: " المحتويات",
    setTimeTodayPrayer:
      "اضبط الوقت الذي ترغب في الانتقال فيه إلى اليوم التالي.",
    update: "تحديث التطبيق",
    noupdates: "لا توجد تحديثات",
    setCurrentDate: "حدد التاريخ الحالي",
    setYear: "حدد السنة",
    changeDate: "حدد التاريخ",
    todayprayerdescription:
      "تتيح خيارات الصلاة اليوم للتطبيق تحميل الصلوات / الالحان التي تقال اليوم تلقائيًا بدلاً من تحميل جميع الخيارات الممكنة",
    FIRST_SUNDAY_OF_KIAHK: "الأسبوع الاول من شهر كيهك",
    SECOND_SUNDAY_OF_KIAHK: "الأسبوع الثاني من شهر كيهك",
    THIRD_SUNDAY_OF_KIAHK: "الأسبوع الثالث من شهر كيهك",
    FOURTH_SUNDAY_OF_KIAHK: "الأسبوع الرابع من شهر كيهك",
    NATIVITY: "عيد الميلاد",
    EPIPHANY: "عيد الغطاس",
    EPIPHANY_SECONDDAY: "ثاني يوم عيد الغطاس",
    NATIVITY_SECONDDAY: "ثاني يوم عيد الميلاد",
    AddBishops: "أضف الأساقفة",
    ANNUNCIATION: "عيد البشارة",
    RESURRECTION: "عيد القيامة",
    PALM_SUNDAY: "احد الشعانين",
    ASCENSION: "عيد الصعود",
    ASCENSIONTOPENTECOST: "الفترة من الصعود إلى عيد العنصرة",
    PENTECOST: "عيد العنصرة",
    FEAST_OF_CIRCUMCISION: "عيد الختان",
    ENTRY_EGYPT: "عيد دخول المسيح ارض مصر",
    WEDDING_CANA: "عيد عرس قانا الجليل",
    PRESENTATION_TEMPLE: "عيد دخول المسيح",
    TRANSFIGURATION: "عيد التجلي",
    COVENANT_THURSDAY: "خميس العهد",
    THOMAS_SUNDAY: "احد توما",
    ASSUMPTION_STMARY: "عيد العذراء",
    FEAST_OF_APOSTLES: "عيد الرسل",
    COPTIC_NEW_YEAR: "عيد النيروز",
    FEAST_OF_CROSS: "عيد الصليب",
    FEAST_OF_CROSS_3: "عيد الصليب (3)",
    GREAT_LENT: "الصوم الكبير",
    HOLY_WEEK: " اسبوع الالام",
    FAST_OF_APOSTLES: "صوم الرسل",
    FAST_STMARY: "صوم العذراء",
    NATIVITY_FAST: "صوم الميلاد",
    GOOD_FRIDAY: "الجمعة العظيمة",
    LAZARUS_SATURDAY: "سبت لعازر",
    JONAH_FEAST: "فصح يونان",
    JONAH_FAST: "صوم يونان",
    HOLY_50: "الخماسين المقدس",
    NATIVITY_PARAMOUN: "برمون الميلاد",
    EPIPHANY_PARAMOUN: "برمون الغطاس",
    NATIVITY_PERIOD: "بين عيد الميلاد و الختان",
    week_of: "الإسبوع ال",
    ST_MARY: "العزراء مريم",
    ARCHANGEL_MICHAEL: "الملاك ميخائيل",
    ARCHANGEL_GABRIEL: "الملاك غبريال",
    ARCHANGEL_RAPHAEL: "الملاك روفائيل",
    FOUR_INCORPOREAL_CREATURES: "الربعة حيوانات غير المتجسدين",
    TWENTY_FOUR_PRIESTS: "الاربعة وعشرين قسيساً",
    ST_JOHN_BELOVED: "القديس يوحنا الأنجيلي",
    ST_THEODORE_SHOTEP: "الأمير تادرس بن يوحنا الشطبي ",
    APAKIR_AND_JOHN: " أباكير ويوحنا اخوه",
    COSMAN_AND_DEMIAN: "الشهيدان قزمان و دميان",
    ST_BARBARA: "الشهيدة بربارة",
    ST_JULIANA: "الشهيدة يوليانة",
    MACARIUS_GREAT: "الأنبا مقار الكبير",
    ATHANASIUS_APOSTOLIC: " الانبا اثناسيوس الرسولي ",
    MAXIMUS_DOMETIUS: "مكسيموس ودوماديوس",
    ST_PACHOMIOUS: "انبا باخوميوس ",
    ST_SHENOUDA_ARCHMANDRITE: "الانبا شنودة رئيس المتوحدين",
    SAMUEL_CONFESSOR: "انبا صموئيل المعترف",
    JOHN_THE_BAPTIST: "يوحنا المعمدان",
    ST_MARK: "مارمرقس الرسول",
    ST_STEPHEN: "الشهيد استفانوس",
    ST_GEORGE: "الشهيد مارجرجس",
    ST_PHILOPATER: "الشهيد مرقوريوس",
    ST_MINA: "الشهيد مارمينا",
    ST_ABANOUB: "الشهيد ابانوب",
    ST_DEMIANA: "الشهيدة دميانه",
    ST_MARINA: "الشهيدة مارينا",
    ST_ANTHONY: "الأنبا أنطونيوس",
    ST_PAULHERMIT: "الأنبا بولا",
    ST_MOSES: "الأنبا موسى",
    ST_PISHOI: "الأنبا بيشوي",
    ST_REWIS: "الأنبا رويس",
    ST_KARAS: "الأنبا كاراس",
    ST_JOHN_THE_SHORT: "الأنبا يوحنا القصير",
    ST_KIROLLOS_SIXTH: "البابا كيرلس",
  },
};

export default Languages;
